model:
  target: evomerge.HeronV1
  params:
    model_path: turing-motors/heron-chat-blip-ja-stablelm-base-7b-v1-llava-620k
    # model_path: turing-motors/heron-chat-blip-ja-stablelm-base-7b-v1
    template: ja-heron-v1
    model_kwargs:
      torch_dtype: torch.float16
    generation_config:
      max_new_tokens: 512
      do_sample: false
      num_beams: 5
      repetition_penalty: 1.5
      # config in their readme
      # temperature: 0.0
      # no_repeat_ngram_size: 2
eval:
    - target: evomerge.eval.JaVGVQA
      params:
        loader_kwargs:
          batch_size: 1
          num_workers: 2
    - target: evomerge.eval.JaVLMBenchIntheWild
      params:
        loader_kwargs:
          batch_size: 1
          num_workers: 2