model:
  target: evomerge.CausalLMWithvLLM
  params:
    model_path: WizardLM/WizardMath-7B-V1.1
    model_kwargs:
      dtype: bfloat16
    template: ja-alpaca-cot
  
eval:
  target: evomerge.eval.JaMGSM