model:
  target: evomerge.CausalLMWithvLLM
  params:
    model_path: /root/.cache/huggingface/hub/models--new_model
    model_kwargs:
      trust_remote_code: true
      enforce_eager: true
      dtype: bfloat16
    template: ja-alpaca-cot
eval:
  target: evomerge.eval.JaMGSM